// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zEJSqV0Qz5EGAACGMFWeoXhkp7Gry_A',
    appId: '1:760658289906:web:0ae7277936cf1264abdc6b',
    messagingSenderId: '760658289906',
    projectId: 'empower-d4c48',
    authDomain: 'empower-d4c48.firebaseapp.com',
    storageBucket: 'empower-d4c48.appspot.com',
    measurementId: 'G-QEMHVNB4SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg7t9BZcFRa1sA4Y0JEfGAdtUw03pfE0M',
    appId: '1:760658289906:android:4666c760a1a1117dabdc6b',
    messagingSenderId: '760658289906',
    projectId: 'empower-d4c48',
    storageBucket: 'empower-d4c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLKgDSLvZ1D5ATCr78ca9KevSs2VCFDaU',
    appId: '1:760658289906:ios:44264c2bedd37740abdc6b',
    messagingSenderId: '760658289906',
    projectId: 'empower-d4c48',
    storageBucket: 'empower-d4c48.appspot.com',
    iosBundleId: 'com.example.empower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLKgDSLvZ1D5ATCr78ca9KevSs2VCFDaU',
    appId: '1:760658289906:ios:44264c2bedd37740abdc6b',
    messagingSenderId: '760658289906',
    projectId: 'empower-d4c48',
    storageBucket: 'empower-d4c48.appspot.com',
    iosBundleId: 'com.example.empower',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7zEJSqV0Qz5EGAACGMFWeoXhkp7Gry_A',
    appId: '1:760658289906:web:aabed61d985339f8abdc6b',
    messagingSenderId: '760658289906',
    projectId: 'empower-d4c48',
    authDomain: 'empower-d4c48.firebaseapp.com',
    storageBucket: 'empower-d4c48.appspot.com',
    measurementId: 'G-B376Z5HVPV',
  );
}
